// 'use client';

import './globals.css';
import '@mantine/core/styles.css';
import { Inter } from 'next/font/google';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';

export const metadata = {
    title: 'Miniature Spork',
    description: 'Generated by create next app'
};
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                <MantineProvider defaultColorScheme="light">{children}</MantineProvider>
            </body>
        </html>
    );
}
