'use client';
import Head from 'next/head';
import { Box, Center, Container } from '@mantine/core';

export default function Home() {
    return (
        <>
            <Head>
                <title>Miniature Spork</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container className="box">
                <Center h={724} mx="auto">
                    <Box>Jakaś lista zakupów .</Box>
                </Center>
            </Container>
        </>
    );
}
