'use client';
import Head from 'next/head';
import { Box, Button, Center, Container, NavLink } from '@mantine/core';
import Link from 'next/link';

export default function Home() {
    return (
        <>
            <Head>
                <title>Miniature Spork</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container className="box">
                <Center h={724} mx="auto">
                    <Link href="/shopping-list" passHref>
                        <Button>Jakaś lista zakupów</Button>
                    </Link>
                </Center>
            </Container>
        </>
    );
}
